apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    app: mongodb
    project: roboshop
    tier: db
spec:
  selector:
    matchLabels:
      app: mongodb
      project: roboshop
      tier: db
  serviceName: "mongodb"
  replicas: {{ .Values.statefulset.replicas }}
  template:
    metadata:
      labels:
        app: mongodb
        project: roboshop
        tier: db
    spec:
      containers:
      - name: mongodb
        image: "rajesh028/mongodb:{{ .Values.deployment.imageversion }}"
        ports:
        - containerPort: 27017
          name: mongodb
          protocol: TCP          # ✅ Correct here
        volumeMounts:
        - name: mongodb
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 1Gi

